version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./acme-challenge:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./acme:/etc/acme.sh

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./acme:/etc/acme.sh
      - ./acme-challenge:/usr/share/nginx/html

  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    restart: unless-stopped
    expose:
      - "4533"
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
    volumes:
      - ./data:/data
      - ./music_mp3:/music

  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    expose:
       - "8384"
    restart: unless-stopped
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "21027:21027/udp"
    volumes:
      - ./syncthing/config:/var/syncthing/config
      - ./music:/var/syncthing/music
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=syncthing.${DOMAIN}
      - LETSENCRYPT_HOST=syncthing.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}

  flac2mp3:
    build: ./flac-to-mp3
    container_name: flac2mp3
    restart: unless-stopped
    volumes:
      - ./music:/music:ro
      - ./music_mp3:/music_mp3
