name: Hetzner Power Scheduler

on:
  schedule:
    # Allumer tous les jours à 08h30 UTC
    - cron: '30 8 * * *'
    # Éteindre tous les jours à 03h00 UTC
    - cron: '0 3 * * *'

jobs:
  power-on:
    if: github.event.schedule == '30 8 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Power ON server
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.HETZNER_TOKEN }}" \
            "https://api.hetzner.cloud/v1/servers/${{ secrets.HETZNER_SERVER_ID }}/actions/poweron"

  power-off:
    if: github.event.schedule == '0 3 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Power OFF server
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.HETZNER_TOKEN }}" \
            "https://api.hetzner.cloud/v1/servers/${{ secrets.HETZNER_SERVER_ID }}/actions/shutdown"
